import Head from 'next/head';
import { Josefin_Sans } from '@next/font/google';
import { Card } from '@/components/Card';
import { useState } from 'react';

export default function Home() {
  const [condition, setCondition] = useState<string>('veryUnhealthy');

  let background = './images/good.jpeg';

  switch (condition) {
    case 'good':
      background = './images/good.jpeg';
      break;
    case 'moderate':
      background = './images/moderate.jpeg';
      break;
    case 'someUnhealthy':
      background = './images/unhealthy-1.jpeg';
      break;
    case 'unhealthy':
      background = './images/unhealthy-2.jpeg';
      break;
    case 'veryUnhealthy':
      background = './images/unhealthy-3.jpeg';
      break;
    case 'hazardous':
      background = './images/hazardous.jpeg';
      break;
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta
          name='description'
          content='Generated by create next app'
        />
        <meta
          name='viewport'
          content='width=device-width, initial-scale=1'
        />
        <link
          rel='icon'
          href='/favicon.ico'
        />
      </Head>
      <main
        data-theme={condition}
        style={{
          background: `url(${background}) no-repeat center/cover`
        }}
        className='relative grid w-full place-items-center text-text'>
        <Card />
      </main>
    </>
  );
}
